2024-04-03 13:56:43,124:DEBUG - psycopg.pq couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 13:56:44,255:INFO - django.utils.autoreload Watching for file changes with StatReloader)
2024-04-03 13:57:11,641:INFO - django.utils.autoreload /app/config/settings/base.py changed, reloading.)
2024-04-03 13:57:19,852:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 13:57:20,644:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:02:09,887:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-04-03 14:02:12,357:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:02:13,266:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:02:16,884:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-04-03 14:02:19,022:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:02:19,903:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:03:08,735:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-04-03 14:03:11,555:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:03:12,321:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:03:45,626:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-04-03 14:03:47,641:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:03:48,419:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:03:58,759:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-04-03 14:04:00,686:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:04:01,435:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:04:05,359:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-04-03 14:04:07,269:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:04:08,033:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:04:11,944:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-04-03 14:04:13,685:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:04:14,412:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:04:25,343:INFO - django.utils.autoreload autoreload.py (line 266. /app/config/settings/base.py changed, reloading.)
2024-04-03 14:41:41,332:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:41:44,459:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:41:45,437:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:42:03,972:WARNING - django.request log.py (line 241. Not Found: /favicon.ico)
2024-04-03 14:43:44,575:ERROR - django.request log.py (line 241. Internal Server Error: /admin/playlists/playlistanime/2fff272b-4742-482d-8e96-cf40dd97df82/change/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1944, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1257, in save_model
    obj.save()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 924, in save_base
    post_save.send(
  File "/usr/local/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/playlists/models.py", line 91, in update_anime_stats_on_favorite
    anime.num_list_users += 1
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'
2024-04-03 14:45:10,962:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 14:45:12,854:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:45:13,879:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:46:00,456:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/models.py changed, reloading.)
2024-04-03 14:46:02,914:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:46:03,723:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:47:34,937:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:47:54,728:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:48:10,413:ERROR - django.request log.py (line 241. Internal Server Error: /admin/playlists/playlistanime/2fff272b-4742-482d-8e96-cf40dd97df82/change/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1944, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1257, in save_model
    obj.save()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 924, in save_base
    post_save.send(
  File "/usr/local/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/playlists/models.py", line 91, in update_anime_stats_on_favorite
    anime.num_list_users += 1
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'
2024-04-03 14:48:31,475:ERROR - django.request log.py (line 241. Internal Server Error: /admin/playlists/playlistanime/2fff272b-4742-482d-8e96-cf40dd97df82/change/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1944, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1257, in save_model
    obj.save()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 924, in save_base
    post_save.send(
  File "/usr/local/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/playlists/models.py", line 91, in update_anime_stats_on_favorite
    anime.num_list_users += 1
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'
2024-04-03 14:49:22,648:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 14:49:24,574:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:49:25,333:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:49:33,664:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 14:49:35,622:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:49:36,593:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:53:23,276:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 14:53:25,192:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:53:25,755:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:53:41,667:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 14:53:43,705:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:53:44,557:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:54:03,090:ERROR - django.request log.py (line 241. Internal Server Error: /admin/playlists/playlistanime/2fff272b-4742-482d-8e96-cf40dd97df82/change/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1944, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1257, in save_model
    obj.save()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 924, in save_base
    post_save.send(
  File "/usr/local/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/playlists/models.py", line 95, in update_anime_stats_on_favorite
    anime.num_list_users -= 1 if anime.num_list_users is not None and anime.num_list_users > 0 else 0
    ^^^^^
UnboundLocalError: cannot access local variable 'anime' where it is not associated with a value
2024-04-03 14:54:18,052:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 14:54:20,232:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:54:21,046:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 14:58:55,596:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 14:58:57,571:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 14:58:58,425:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:05:58,810:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/models.py changed, reloading.)
2024-04-03 15:06:00,786:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:06:01,571:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:06:05,959:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/models.py changed, reloading.)
2024-04-03 15:06:07,659:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:06:08,415:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:06:16,497:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/models.py changed, reloading.)
2024-04-03 15:06:18,413:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:06:19,267:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:06:26,001:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/models.py changed, reloading.)
2024-04-03 15:06:27,703:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:06:28,458:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:07:27,386:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/models.py changed, reloading.)
2024-04-03 15:07:29,900:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:07:30,774:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:08:09,040:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:08:32,282:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/admin.py changed, reloading.)
2024-04-03 15:08:34,123:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:08:34,950:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:08:40,522:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/admin.py changed, reloading.)
2024-04-03 15:08:42,496:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:08:43,236:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:09:05,630:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:09:17,390:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:10:05,069:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/admin.py changed, reloading.)
2024-04-03 15:10:07,115:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:10:07,989:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:10:12,496:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/admin.py changed, reloading.)
2024-04-03 15:10:14,529:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:10:15,584:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:10:40,837:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 15:10:42,863:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:10:43,571:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:11:02,542:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 15:11:04,395:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:11:05,148:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:11:14,932:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 15:11:16,734:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:11:17,444:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:12:40,408:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 15:12:42,139:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:12:42,867:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:13:39,424:ERROR - django.request log.py (line 241. Internal Server Error: /admin/playlists/playlistanime/8b81e7bb-83f2-4925-bebd-ca8f168f83bb/change/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1944, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1257, in save_model
    obj.save()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 924, in save_base
    post_save.send(
  File "/usr/local/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/playlists/models.py", line 91, in update_anime_stats_on_favorite
    anime.num_list_users += 1
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'
2024-04-03 15:14:05,131:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 15:14:07,061:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:14:07,785:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:14:19,088:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 15:14:21,186:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:14:21,984:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:54:03,025:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 15:54:05,386:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:54:06,193:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:54:15,827:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 15:54:18,326:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:54:19,066:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:55:49,864:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/models.py changed, reloading.)
2024-04-03 15:55:51,807:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:55:52,532:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:58:00,993:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/apps.py changed, reloading.)
2024-04-03 15:58:02,927:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:58:03,826:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:58:14,107:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/apps.py changed, reloading.)
2024-04-03 15:58:15,928:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:58:16,676:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 15:58:56,028:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/apps.py changed, reloading.)
2024-04-03 15:58:57,966:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 15:58:58,851:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 16:02:51,283:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 16:02:53,181:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 16:02:54,162:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 16:06:19,259:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/admin.py changed, reloading.)
2024-04-03 16:06:21,322:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 16:06:22,265:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 16:06:42,322:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/admin.py changed, reloading.)
2024-04-03 16:06:44,458:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 16:06:45,761:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 16:10:17,560:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 16:10:19,774:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 16:10:20,516:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 16:11:09,849:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 16:11:11,795:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 16:11:12,587:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 16:11:31,859:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 16:11:34,125:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 16:11:34,876:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 16:11:40,016:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 16:11:41,802:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 16:11:42,595:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 16:12:17,268:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 16:12:19,156:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 16:12:19,903:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 16:12:24,012:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 16:12:25,781:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 16:12:26,505:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 13:23:36,525:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 13:26:38,786:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:14:03,469:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:14:07,015:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:14:08,049:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:14:47,535:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:14:50,398:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:14:51,068:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:14:57,193:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:14:59,613:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:15:00,272:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:15:40,749:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:15:42,889:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:15:43,575:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:15:49,159:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:15:51,582:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:15:52,263:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:16:04,190:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:16:06,580:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:16:07,869:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:16:13,347:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:16:15,338:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:16:16,560:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:18:22,617:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:18:24,813:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:18:25,702:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:18:33,309:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:18:35,612:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:18:36,617:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:18:42,016:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:18:44,227:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:18:45,171:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:19:30,167:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:19:45,063:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/admin.py changed, reloading.)
2024-04-03 17:19:48,058:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:19:49,305:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:20:19,439:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:21:33,992:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:21:35,889:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:21:36,597:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:21:49,524:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:22:01,416:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:23:45,082:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:23:48,896:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:23:50,885:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:24:28,893:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:24:50,221:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:25:09,677:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:25:46,904:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:25:49,413:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:25:50,514:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:25:58,914:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:26:52,427:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:26:55,400:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:26:56,489:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:27:02,365:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:27:04,578:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:27:05,697:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:27:10,741:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:27:13,560:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:27:14,796:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:27:20,283:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:27:22,719:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:27:23,748:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:28:06,140:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:29:08,089:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:29:10,295:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:29:11,199:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:29:31,028:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:29:33,845:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:29:34,773:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:29:46,745:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:29:48,637:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:29:49,362:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:32:17,137:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:32:19,131:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:32:20,036:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:32:58,520:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:33:00,482:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:33:01,179:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:33:03,906:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:33:06,092:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:33:06,953:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:33:10,011:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:33:12,317:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:33:12,999:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:33:16,208:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:33:18,055:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:33:18,650:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:33:20,607:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:33:22,998:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:33:23,746:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:33:27,155:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:33:29,423:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:33:30,042:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:33:34,341:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:33:36,959:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:33:38,009:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:33:48,396:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:33:50,346:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:33:51,132:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:40:21,516:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:42:08,718:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:42:23,182:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:43:11,730:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:43:19,839:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:43:21,324:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:44:38,429:WARNING - django.request log.py (line 241. Not Found: /admin/reviews/review/)
2024-04-03 17:47:57,440:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:47:59,957:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:48:02,250:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:48:08,485:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:48:11,216:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:48:12,540:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:48:17,986:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:48:21,407:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:48:22,981:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:48:48,213:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:48:50,591:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:48:51,395:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:48:56,329:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:48:59,058:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:49:00,164:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:49:07,663:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:49:09,694:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:49:10,512:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:49:37,672:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:49:40,395:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:49:41,823:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:50:11,162:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:50:13,494:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:50:14,864:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 17:50:27,907:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/models.py changed, reloading.)
2024-04-03 17:50:29,933:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 17:50:31,029:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:29:41,506:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/admin.py changed, reloading.)
2024-04-03 18:29:43,816:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:29:44,649:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:34:12,310:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/reviews/admin.py changed, reloading.)
2024-04-03 18:34:14,644:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:34:15,536:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:36:19,280:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:36:23,658:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:36:24,875:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:42:02,114:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 18:42:04,409:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:42:05,411:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:43:26,687:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/models.py changed, reloading.)
2024-04-03 18:43:28,739:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:43:29,881:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:43:36,662:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/models.py changed, reloading.)
2024-04-03 18:43:38,830:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:43:39,662:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:43:59,408:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/models.py changed, reloading.)
2024-04-03 18:44:01,625:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:44:02,625:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:44:22,811:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/models.py changed, reloading.)
2024-04-03 18:44:25,187:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:44:26,053:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:46:05,620:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:46:29,571:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/admin.py changed, reloading.)
2024-04-03 18:46:31,460:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:46:32,208:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:46:42,283:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/contents/admin.py changed, reloading.)
2024-04-03 18:46:45,321:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:46:46,257:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:48:34,311:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:48:51,837:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:54:14,687:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 18:54:16,643:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:54:17,570:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:54:21,539:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 18:54:23,272:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:54:24,186:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:54:59,518:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 18:55:01,472:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:55:02,497:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:55:07,643:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 18:55:09,787:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:55:10,543:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:55:23,006:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 18:55:25,030:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:55:25,831:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:55:31,696:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 18:55:33,484:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:55:34,239:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 18:55:46,913:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 18:55:49,341:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 18:55:50,530:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
2024-04-03 19:02:29,756:DEBUG - PIL.Image Image.py (line 363. Importing BlpImagePlugin)
2024-04-03 19:02:29,759:DEBUG - PIL.Image Image.py (line 363. Importing BmpImagePlugin)
2024-04-03 19:02:29,759:DEBUG - PIL.Image Image.py (line 363. Importing BufrStubImagePlugin)
2024-04-03 19:02:29,764:DEBUG - PIL.Image Image.py (line 363. Importing CurImagePlugin)
2024-04-03 19:02:29,765:DEBUG - PIL.Image Image.py (line 363. Importing DcxImagePlugin)
2024-04-03 19:02:29,767:DEBUG - PIL.Image Image.py (line 363. Importing DdsImagePlugin)
2024-04-03 19:02:29,775:DEBUG - PIL.Image Image.py (line 363. Importing EpsImagePlugin)
2024-04-03 19:02:29,780:DEBUG - PIL.Image Image.py (line 363. Importing FitsImagePlugin)
2024-04-03 19:02:29,781:DEBUG - PIL.Image Image.py (line 363. Importing FliImagePlugin)
2024-04-03 19:02:29,783:DEBUG - PIL.Image Image.py (line 363. Importing FpxImagePlugin)
2024-04-03 19:02:29,785:DEBUG - PIL.Image Image.py (line 366. Image: failed to import FpxImagePlugin: No module named 'olefile')
2024-04-03 19:02:29,786:DEBUG - PIL.Image Image.py (line 363. Importing FtexImagePlugin)
2024-04-03 19:02:29,788:DEBUG - PIL.Image Image.py (line 363. Importing GbrImagePlugin)
2024-04-03 19:02:29,789:DEBUG - PIL.Image Image.py (line 363. Importing GifImagePlugin)
2024-04-03 19:02:29,790:DEBUG - PIL.Image Image.py (line 363. Importing GribStubImagePlugin)
2024-04-03 19:02:29,791:DEBUG - PIL.Image Image.py (line 363. Importing Hdf5StubImagePlugin)
2024-04-03 19:02:29,793:DEBUG - PIL.Image Image.py (line 363. Importing IcnsImagePlugin)
2024-04-03 19:02:29,796:DEBUG - PIL.Image Image.py (line 363. Importing IcoImagePlugin)
2024-04-03 19:02:29,799:DEBUG - PIL.Image Image.py (line 363. Importing ImImagePlugin)
2024-04-03 19:02:29,801:DEBUG - PIL.Image Image.py (line 363. Importing ImtImagePlugin)
2024-04-03 19:02:29,803:DEBUG - PIL.Image Image.py (line 363. Importing IptcImagePlugin)
2024-04-03 19:02:29,804:DEBUG - PIL.Image Image.py (line 363. Importing JpegImagePlugin)
2024-04-03 19:02:29,806:DEBUG - PIL.Image Image.py (line 363. Importing Jpeg2KImagePlugin)
2024-04-03 19:02:29,807:DEBUG - PIL.Image Image.py (line 363. Importing McIdasImagePlugin)
2024-04-03 19:02:29,808:DEBUG - PIL.Image Image.py (line 363. Importing MicImagePlugin)
2024-04-03 19:02:29,810:DEBUG - PIL.Image Image.py (line 366. Image: failed to import MicImagePlugin: No module named 'olefile')
2024-04-03 19:02:29,810:DEBUG - PIL.Image Image.py (line 363. Importing MpegImagePlugin)
2024-04-03 19:02:29,814:DEBUG - PIL.Image Image.py (line 363. Importing MpoImagePlugin)
2024-04-03 19:02:29,830:DEBUG - PIL.Image Image.py (line 363. Importing MspImagePlugin)
2024-04-03 19:02:29,831:DEBUG - PIL.Image Image.py (line 363. Importing PalmImagePlugin)
2024-04-03 19:02:29,834:DEBUG - PIL.Image Image.py (line 363. Importing PcdImagePlugin)
2024-04-03 19:02:29,836:DEBUG - PIL.Image Image.py (line 363. Importing PcxImagePlugin)
2024-04-03 19:02:29,837:DEBUG - PIL.Image Image.py (line 363. Importing PdfImagePlugin)
2024-04-03 19:02:29,848:DEBUG - PIL.Image Image.py (line 363. Importing PixarImagePlugin)
2024-04-03 19:02:29,849:DEBUG - PIL.Image Image.py (line 363. Importing PngImagePlugin)
2024-04-03 19:02:29,850:DEBUG - PIL.Image Image.py (line 363. Importing PpmImagePlugin)
2024-04-03 19:02:29,851:DEBUG - PIL.Image Image.py (line 363. Importing PsdImagePlugin)
2024-04-03 19:02:29,853:DEBUG - PIL.Image Image.py (line 363. Importing QoiImagePlugin)
2024-04-03 19:02:29,854:DEBUG - PIL.Image Image.py (line 363. Importing SgiImagePlugin)
2024-04-03 19:02:29,856:DEBUG - PIL.Image Image.py (line 363. Importing SpiderImagePlugin)
2024-04-03 19:02:29,857:DEBUG - PIL.Image Image.py (line 363. Importing SunImagePlugin)
2024-04-03 19:02:29,859:DEBUG - PIL.Image Image.py (line 363. Importing TgaImagePlugin)
2024-04-03 19:02:29,861:DEBUG - PIL.Image Image.py (line 363. Importing TiffImagePlugin)
2024-04-03 19:02:29,862:DEBUG - PIL.Image Image.py (line 363. Importing WebPImagePlugin)
2024-04-03 19:02:29,866:DEBUG - PIL.Image Image.py (line 363. Importing WmfImagePlugin)
2024-04-03 19:02:29,868:DEBUG - PIL.Image Image.py (line 363. Importing XbmImagePlugin)
2024-04-03 19:02:29,870:DEBUG - PIL.Image Image.py (line 363. Importing XpmImagePlugin)
2024-04-03 19:02:29,872:DEBUG - PIL.Image Image.py (line 363. Importing XVThumbImagePlugin)
2024-04-03 19:03:09,648:ERROR - django.request log.py (line 241. Internal Server Error: /admin/playlists/playlistmanga/add/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1941, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1257, in save_model
    obj.save()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 924, in save_base
    post_save.send(
  File "/usr/local/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/apps/playlists/signals.py", line 33, in update_manga_on_favorite
    manga = instance.anime
            ^^^^^^^^^^^^^^
AttributeError: 'PlaylistManga' object has no attribute 'anime'
2024-04-03 19:03:28,459:INFO - django.utils.autoreload autoreload.py (line 266. /app/apps/playlists/signals.py changed, reloading.)
2024-04-03 19:03:30,754:DEBUG - psycopg.pq __init__.py (line 66. couldn't import psycopg 'c' implementation: No module named 'psycopg_c')
2024-04-03 19:03:31,632:INFO - django.utils.autoreload autoreload.py (line 668. Watching for file changes with StatReloader)
